name: build
on:
  push:
    branches:
      - "**"
    paths-ignore:
      - ".gitignore"
      - ".envrc"
      - "README.md"
      - "CONTRIBUTING.md"
      - ".github/workflows/labels.yml"
      - ".github/labels.toml"
      - ".github/**/*.md"
    tags-ignore:
      - "v*"
  pull_request:
jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - "py36"
          - "py37"
          - "py38"
          - "py39"
          - "flake8"
          - "mypy"

        include:
          - environment: "py36"
            python: "3.6"
          - environment: "py37"
            python: "3.7"
          - environment: "py38"
            python: "3.8"
          - environment: "py39"
            python: "3.9"
          - environment: "flake8"
            python: "3.9"
          - environment: "mypy"
            python: "3.9"

    container:
      image: python:${{ matrix.python }}

    steps:
      - uses: actions/checkout@master
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - name: Run tox
        run: |
          tox -e ${{ matrix.environment }}

  # Build docker images
  docker:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Docker Lint
        run: make docker-lint

      - name: Install pytoml
        run: pip3 install pytoml --user

      - name: Download BuildX
        run: |
          curl -sSfL https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64 -o buildx
          mkdir -p ${HOME}/.docker/cli-plugins
          cp buildx ${HOME}/.docker/cli-plugins/docker-buildx
          chmod a+x ${HOME}/.docker/cli-plugins/docker-buildx

      - name: Install
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y -qq qemu-user
          sudo docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64

      - name: Info
        run: |
          cat /proc/sys/fs/binfmt_misc/qemu-aarch64
          docker info
          docker buildx version

      - name: Create Builder
        run: |
          docker buildx create --name actions
          docker buildx use actions
          docker buildx inspect --bootstrap

      - name: Docker Login to Registry (DockerHub)
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        env:
          DOCKER_USERNAME: asaharan3
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        if: github.event_name	== 'push'

      - name: Docker Build [With Push]
        run: |
          make debug-docker-vars
          make docker
          make docker-inspect
        env:
          BUILDX_PUSH: 1
          BUILDX_ENABLE: 1
        if: github.event_name == 'push'

      # No Push
      - name: Docker Build [Skip Push]
        run: |
          make debug-docker-vars
          make docker
        env:
          BUILDX_PUSH: 0
          BUILDX_ENABLE: 1
        if: github.event_name == 'pull_request'

      - name: Docker Cleanup
        run: |
          docker logout || true
          rm -f ${HOME}/.docker/config.json
        if: github.event_name	== 'push'
